export const ADD_ONE_TO_REPEAT = 'YOUTUBE/ADD_ONE_TO_REPEAT';

export const MINUS_ONE_TO_REPEAT = 'YOUTUBE/MINUS_ONE_TO_REPEAT';

export const SET_LINKS = 'YOUTUBE/SET_LINKS';

export const ADD_LINK = 'YOUTUBE/ADD_LINK';

export const REMOVE_LINK = 'YOUTUBE/REMOVE_LINK';

export const SET_LINK = 'YOUTUBE/SET_LINK';

export const SET_LINK_TITLE = 'YOUTUBE/SET_LINK_TITLE';
